// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaphaMovies.API.Data;

#nullable disable

namespace RaphaMovies.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251223200739_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaphaMovies.API.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BackdropUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(3,1)");

                    b.Property<decimal>("RentalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrailerUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Genre");

                    b.HasIndex("Title");

                    b.HasIndex("Year");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333001"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "3h 1min",
                            Genre = "Drama",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
                            IsAvailable = true,
                            Rating = 8.9m,
                            RentalPrice = 14.99m,
                            Synopsis = "A história do físico J. Robert Oppenheimer e seu papel no desenvolvimento da bomba atômica.",
                            Title = "Oppenheimer",
                            TrailerUrl = "https://www.youtube.com/watch?v=uYPbbksJxIg",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333002"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "2h 47min",
                            Genre = "Ficção Científica",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
                            IsAvailable = true,
                            Rating = 8.8m,
                            RentalPrice = 15.99m,
                            Synopsis = "Paul Atreides se une aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família.",
                            Title = "Duna: Parte 2",
                            TrailerUrl = "https://www.youtube.com/watch?v=Way9Dexny3w",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333003"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/bQS43HSLZzMjZkcHJz4fGc7fNdz.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "2h 21min",
                            Genre = "Comédia",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg",
                            IsAvailable = true,
                            Rating = 8.4m,
                            RentalPrice = 12.99m,
                            Synopsis = "A história de Bella Baxter, uma jovem trazida de volta à vida pelo brilhante cientista Dr. Godwin Baxter.",
                            Title = "Pobres Criaturas",
                            TrailerUrl = "https://www.youtube.com/watch?v=RlbR5N6veqw",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333004"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/1X7vow16X7CnCoexXh4H4F2yDJv.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "3h 26min",
                            Genre = "Crime",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/dB6Krk806zeqd0YNp2ngQ9zXteH.jpg",
                            IsAvailable = true,
                            Rating = 8.1m,
                            RentalPrice = 13.99m,
                            Synopsis = "Membros da tribo Osage nos EUA são assassinados sob circunstâncias misteriosas nos anos 1920.",
                            Title = "Assassinos da Lua das Flores",
                            TrailerUrl = "https://www.youtube.com/watch?v=EP34Yoxs3FQ",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333005"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/nHf61UzkfFno5X1ofIhugCPus2R.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "1h 54min",
                            Genre = "Comédia",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg",
                            IsAvailable = true,
                            Rating = 7.8m,
                            RentalPrice = 11.99m,
                            Synopsis = "Barbie sofre uma crise existencial e parte em uma jornada de autodescoberta no mundo real.",
                            Title = "Barbie",
                            TrailerUrl = "https://www.youtube.com/watch?v=pBk4NYhWNMM",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333006"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/9jPoyxjiEYPylUIMI3Ntixf8z3M.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "2h 32min",
                            Genre = "Suspense",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/kQs6keheMwCxJxrzV83VUwFtHkB.jpg",
                            IsAvailable = true,
                            Rating = 8.2m,
                            RentalPrice = 12.99m,
                            Synopsis = "Uma escritora é suspeita de assassinar seu marido quando ele é encontrado morto.",
                            Title = "Anatomia de uma Queda",
                            TrailerUrl = "https://www.youtube.com/watch?v=MJlpBrQKCBc",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333007"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "2h 20min",
                            Genre = "Animação",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
                            IsAvailable = true,
                            Rating = 8.7m,
                            RentalPrice = 14.99m,
                            Synopsis = "Miles Morales atravessa o Multiverso e encontra uma equipe de Homens-Aranha.",
                            Title = "Homem-Aranha: Através do Aranhaverso",
                            TrailerUrl = "https://www.youtube.com/watch?v=shW9i6k8cB0",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333008"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/64e7jXfNRaFrPCnWjSHdNxBmaAA.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "1h 47min",
                            Genre = "Terror",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/v31MsWhF9WFh7Qo09IvbZOFQ03y.jpg",
                            IsAvailable = true,
                            Rating = 7.5m,
                            RentalPrice = 10.99m,
                            Synopsis = "Um casal viaja para uma ilha remota para comer em um restaurante exclusivo com um chef famoso.",
                            Title = "O Menu",
                            TrailerUrl = "https://www.youtube.com/watch?v=C_uTkUGcHv4",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333009"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/AaV1YIdWKhxX5V4FlTxU7S2QXQL.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "2h 11min",
                            Genre = "Ação",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
                            IsAvailable = true,
                            Rating = 8.6m,
                            RentalPrice = 12.99m,
                            Synopsis = "Depois de 30 anos de serviço, Pete Mitchell é convocado para treinar um grupo de pilotos de elite.",
                            Title = "Top Gun: Maverick",
                            TrailerUrl = "https://www.youtube.com/watch?v=qSqVVswa420",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333010"),
                            BackdropUrl = "https://image.tmdb.org/t/p/original/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Duration = "2h 19min",
                            Genre = "Ficção Científica",
                            ImageUrl = "https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
                            IsAvailable = true,
                            Rating = 8.7m,
                            RentalPrice = 13.99m,
                            Synopsis = "Uma imigrante chinesa descobre que precisa se conectar com versões dela mesma em universos paralelos.",
                            Title = "Tudo em Todo o Lugar ao Mesmo Tempo",
                            TrailerUrl = "https://www.youtube.com/watch?v=wxN1T1uxQ2g",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Year = 2022
                        });
                });

            modelBuilder.Entity("RaphaMovies.API.Models.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RentedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DueDate");

                    b.HasIndex("MovieId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("RaphaMovies.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@raphamovies.com",
                            Name = "Administrador",
                            PasswordHash = "$2a$11$3FvDwFsOIiw4bhhagkEaTuYrjpaWCSQmdMt6bPxYlqNlNUv7SFVYa",
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RaphaMovies.API.Models.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Role = "admin",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("RaphaMovies.API.Models.Rental", b =>
                {
                    b.HasOne("RaphaMovies.API.Models.Movie", "Movie")
                        .WithMany("Rentals")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaphaMovies.API.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RaphaMovies.API.Models.UserRole", b =>
                {
                    b.HasOne("RaphaMovies.API.Models.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RaphaMovies.API.Models.Movie", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("RaphaMovies.API.Models.User", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
